name: firebase
description: Firebase library
version: 0.0.1
author: Rik Bellens <rik.bellens@appsup.be>
homepage: https://github.com/appsup-dart/firebase

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  http: ">=0.11.0 <0.12.0"

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
